apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: votingappproject-worker:latest
        imagePullPolicy: IfNotPresent
        name: worker
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_HOST
          value: "db"
        - name: DB_PASS
          value: "positive"
